### ISSUE TITLE
Building!

### ISSUE THREAD

**Issue by kylelt** [Anuken/uCore#1]
Hi im trying to build Mindustry so I can get the bleeding edge :+1: 

Just ran into a couple of issues including uCore, i have tried using the github gradle dependenciy and compiling a jar and using it as a fileTree dependency

Both of these options give compile errors related to your Bits.java util class
![image](https://user-images.githubusercontent.com/734473/32270694-9fb8738a-bf42-11e7-971e-db52614ae4af.png)

**Comment by Anuken** [comment]
These are most likely caused by an old version of uCore (I change it often, and sometimes don't push as often as I should). Mindustry should compile now; you can either download the newer version of uCore from JITPack and use that or just pull the recent changes to Mindustry, since I added the updated uCore dependency to `build.gradle`.

**Comment by kylelt** [comment]
Works well, `desktop:build` fails because i dont have packr but `desktop:run` works fine thanks for updating
